### ISSUE TITLE
Live demo is not working.

### ISSUE THREAD

**Issue by PooriaFarhad** [uestla/Simplex-Calculator#1]
Hello,

Please check your live demo.
http://simplex.tode.cz/en/

**Comment by uestla** [comment]
Hi, it's working for me, what are the symptoms? :-)

**Comment by PooriaFarhad** [comment]
after submiting the button for the first step, It stops on ajax request. :(
Request URL:http://simplex.tode.cz/en/?do=simplexForm-form-submit
HTTP Response :   ... <title>403 - Přístup odepřen | Endora.cz</title> ...

**Comment by PooriaFarhad** [comment]
for example when i enter value 2 for variable, It stops.
still not working for me :(

**Comment by uestla** [comment]
@PooriaFarhad 
Are you using some VPN service?

**Comment by uestla** [comment]
inactive - closing
