### ISSUE TITLE
Apply a constraint for discrete values

### ISSUE THREAD

**Issue by nepos87** [uestla/Simplex-Calculator#16]
Hello, 
I'm applying this algorithm to solve a diet problem. However, I need to limit the portions of some foods with constraints so that the values can be whole instead of continuous. For example the portion of a particular food is best treated as continuous (for example, rice can be any weight), in which case it should be represented with real-valued variables, or as a discrete unit (such as fruit that is eaten whole), in which case it is best represented by integer-valued variables.
So if, for example, I have a mandarin as a fruit, I want the portions to be limited to one of these specified in the array [50, 100, 150, 200] and I don't want them to be continuous values such as 123gr.
In the constraints you can specify a minimum and maximum range but this is not enough to have only the desired values, example:
$task->addRestriction(new Restriction($variable, Restriction::TYPE_GOE, 50));
$task->addRestriction(new Restriction($variable, Restriction::TYPE_LOE, 200));

Is there a way via constraints to force the algorithm to consider one of these portions instead of any continuous value?

Thank you

**Comment by uestla** [comment]
@nepos87 Hello,

unforutnatelly this is not possible at this moment. I understand what you're trying to achieve, however it would mean to change the logic in `Table` class where the computation happens. I'm not sure I would then be able to determine whether I have already found the optimal solution anyway.

Please feel free to send any suggestions for the changes, even by sendint a Pull Request :-)

Have a great day!

**Comment by uestla** [comment]
@nepos87 Update: Wouldn't be enough to use the program to get an optimal solution of e.g. 123g of mandarin and then round it up manually to one of your specified amounts, i.e. 150g?

Best regards

**Comment by nepos87** [comment]
@uestla Hello,
thanks for the answer, yes at the moment I have to manually round the optimal solution to the closest step between the specified values. The idea was that by providing this logic with constraints within the code the optimal solution might be more accurate than manual rounding at the end.

Best regards

**Comment by uestla** [comment]
@nepos87 I don't have any mathematical background on this, but isn't continuous compuation and rounding at the very end more precise than rounding at every individual solution step?

**Comment by nepos87** [comment]
@uestla Yes, a single final rounding generates less error than multiple roundings for each step, in fact I now only round the optimal final values provided by the algorithm. However, implementing in the initial constraints the discrete values that a variable should assume falls within the branch of integer or mixed linear programming which also use other calculation algorithms to find optimal solutions with discrete values.
My problem I believe is in mixed linear programming and could be solved with constraints using the simplex method.
