### ISSUE TITLE
how to run your program, so that it can run what needs to be changed in the code? , thanks in advance

### ISSUE THREAD

**Issue by cloudgundes** [uestla/Simplex-Calculator#3]
![ss](https://user-images.githubusercontent.com/54842406/64165245-dfebae80-ce6e-11e9-88b6-9f180e73d8fb.PNG)

**Comment by uestla** [comment]
Is that a screenshot of `example.php`?

You just set your functions and let the Solver class solve it. `Solver::getSteps()` returns all steps towards the optimal solution (which is the last one or last two element(s)).

**Comment by cloudgundes** [comment]
yes of course, that's a screenshot from example.php, what should I change? because the program is still not running, even though it's copied example.php but only shows it as shown above. Thank you in advance
![Screenshot_5](https://user-images.githubusercontent.com/54842406/64265789-b52c5380-cf5d-11e9-94da-bee5e78fadbf.jpg)

**Comment by uestla** [comment]
Well in fact it is running since it's showing the result in form of simple variable dump - there's no UI, it is meant to be used in programmatical way.

**Comment by cloudgundes** [comment]
thks sir
