### ISSUE TITLE
How to open this programs

### ISSUE THREAD

**Issue by graymail** [uestla/Simplex-Calculator#5]
How to solve this, I'm confused and can not handle it. Please help me .

![image](https://user-images.githubusercontent.com/45532743/102091395-58526500-3e51-11eb-8a7c-9f68fa2f8160.png)

**Comment by uestla** [comment]
Take a look at the code in the file. There are the definitions for the problem.
What you see in the browser is the solution, which is not really well-formatted for viewing in the browser.

You can either press Ctrl + U to see it as the source code in the browser, or run in in command line via `php example.php`.

**Comment by graymail** [comment]
I don't know, I'm not familiar with programming languages and don't know what you mean. Can you please tell me how I can run the program?

and whether the result is similar to the simplex calculator in http://simplex.tode.cz ?

Thanks

**Comment by uestla** [comment]
The website uses this library to solve the simplex problem.
The example is only showing how you can use the library in your program, so it has no GUI per se.

**Comment by graymail** [comment]
Does that mean I need to design or create my own GUI?
How do you make it like on the web, at least from the process of entering the number of variables to forming max input?

Can you share the GUI with me?

**Comment by uestla** [comment]
You can use it either as a console program or create your own GUI (not necessarily a web GUI).
Unfortunatelly I don't have the source code  for the simplex.tode.cz project on this machine, so I can only wish you luck creating your own ;-)
